
server:
  port: 8080
  servlet:
    context-path: /identity
# Moi api se bat dau bang /identity (VD: /identity/users)
spring:
  application:
      name: EVCharging
    # Ten app, hien thi trong log vo dung khi lam microservice

  datasource:
      url: "jdbc:sqlserver://localhost:1433;databaseName=EVChargingDB;encrypt=false"
      username: sa
      password: 12345
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          spring.jpa.entityManagerFactoryInterface: jakarta.persistence.EntityManagerFactory


  mail:
    host: smtp.gmail.com
    port: 587
    username: tranpham7689@gmail.com   # phải đúng chính xác email
    password: abozeytyxgytqsjb         # App Password 16 ký tự
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          starttls.required: true
          ssl.trust: smtp.gmail.com
jwt:
  secret: your-secret-key
  expiration: 86400000