
server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
      name: EVCharging
    # Ten app, hien thi trong log vo dung khi lam microservice

  datasource:
      url: "jdbc:sqlserver://localhost:1433;databaseName=EVChargingDB;encrypt=false"
      username: sa
      password: 12345
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          spring.jpa.entityManagerFactoryInterface: jakarta.persistence.EntityManagerFactory
  mail:
    host: smtp.gmail.com
    port: 587
    username: tranpham7689@gmail.com
    password: abozeytyxgytqsjb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          starttls.required: true
          ssl.trust: smtp.gmail.com
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 923020885723-s2jqbps9j9rb7vfftbd2adpatvtcvbrq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
jwt:
  secret: O9TclINZGLYWW7TZcm8uAzugCmMZkTzHFsgBS3qfsxk=
  expiration: 86400000
app:
  frontend-url: http://localhost:5173
  base-url: http://localhost:8080